### PR TITLE
Add refresh control

### PR DESCRIPTION
**Pull request by jaggs6**
Closes https://github.com/nachoaIvarez/react-native-scrollable-list/issues/2

Added an optional prop to the ScrollableList `onRefresh`

It handles both promises and function callbacks gracefully

Example of it being used in this project.
https://github.com/jaggs6/rn_circle_ci/blob/master/js/MainScreen.js

### CODE REVIEW

**Comment by jaggs6** [comment]
@nachoalvarez what do you think?

**Comment by jaggs6** [comment]
@nachoaIvarez what do you think?

**Comment by nachoaIvarez** [comment]
@jaggs6: This looks great, thank you so much for taking the time for this. I have one question, how does this approach work with thunk actions? For example, if my callback is dispatching a redux thunk action, is this going to act accordingly? I really like where is this going.

**Comment by jaggs6** [comment]
@nachoaIvarez I have not tried redux thunks yet. But I am sure there will be a way to extend this to work with thunks in future. I have tested this with promises and non promise functions. 

Thanks for creating this project. It has made the view logic much simpler to read and understand and maintain.

**Comment by nachoaIvarez** [comment]
@jaggs6: I added an .eslint config and a travis setup in order to enforce code styling. Let's make sure we get no errors and let's merge it!

**Comment by jaggs6** [comment]
I will fix the lint soon. cheers

**Comment by jaggs6** [comment]
opened a new pull request https://github.com/nachoaIvarez/react-native-scrollable-list/pull/4

**Pull request closed without merging**
